[package]
name = "mat-tauri-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
mat-core = { path = "../core" }
tauri = { version = "2", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
dirs-next = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
